spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to MicroBank loans related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@microbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384