spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to MicroBank loans related QA APIs "
  contactDetails:
    name: "Meloday Chen - QA Lead"
    email: "melody@microbank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371